name: cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alexander Wilde <alexander@salesseek.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pizza_ghost_delivery:
    path: ../api
  prompts: ^1.3.1
  tuple: ^1.0.3
  ansicolor: ^1.0.2
  build_cli_annotations: ^1.1.0
  console: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0+1
  build_cli: ^1.3.5
  build_runner: ^1.7.2
